pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

target 'OwnMoney' do
  config = use_native_modules!

  pod 'react-native-config/Extension', :path => '../node_modules/react-native-config'
  
  # Flags change depending on the env values.
  flags = get_default_flags()

  ENVFILES = {
    'Debug' => '$(PODS_ROOT)/../../.env.development',
    'Release' => '$(PODS_ROOT)/../../.env.production',
  }

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => true,
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => FlipperConfiguration.enabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
end

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    installer.pods_project.build_configurations.each do |config|
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
    end

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|

        if target.name == "React-Core.common-AccessibilityResources"
          target.remove_from_project
        end
        
        if target.name == "react-native-config"
          config.build_settings['ENVFILE'] = ENVFILES[config.name]
        end
      end
    end

    flipper_post_install(installer)
  end